version: "3"

services:
  questinator-fe:
    image: "node:latest"
    container_name: questinator-fe
    restart: always
    working_dir: /home/app
    volumes:
      - ./client:/home/app
    ports:
      - "3000:8080"
    environment:
      NODE_ENV: development
    command: sh -c "npm install && npm rebuild node-sass && npm run serve"
  questinator-api:
    image: "node:latest"
    container_name: questinator-api
    restart: always
    working_dir: /home/app
    volumes:
      - ./server:/home/app
    ports:
      - "3001:3000"
    environment:
      NODE_ENV: development
    command: sh -c "npm install && npm run typeorm migration:run && npm run start:dev"
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    container_name: mysql-db
    restart: always
    ports:
      - "3306:3306"
    command: mysqld --sql_mode="" --default-authentication-plugin=mysql_native_password --explicit_defaults_for_timestamp
    environment:
      MYSQL_DATABASE: questionator
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
