export const resultAllMockRepository = [
  {
    id: '11-22-33',
    contestContenderId: 1,
    questionId: '11',
    generatedQuestion: 'question',
    generatedAnswer: 'answer',
    askedOn: new Date(),
    answeredOn: new Date(1554994558000),
    answer: 'answer',
    score: 3,
    isCorrect: true,
    sessionId: 2,
    session: 2,
  },
  {
    id: '11-22-44',
    contestContenderId: 2,
    questionId: '12',
    generatedQuestion: 'question',
    generatedAnswer: 'answer',
    askedOn: new Date(),
    answeredOn: new Date(1554994678000),
    answer: 'answer',
    score: 3,
    isCorrect: true,
    sessionId: 2,
    session: 2,
  },
];
