export const MAX_ASK_QUESTION_INTERVAL_MS = 20000;

export const MIN_ASK_QUESTION_INTERVAL_MS = 500;

export const INITIAL_ASK_QUESTION_INTERVAL_MS = 10000;

export const ANSWER_WAIT_TIMEOUT_MS = 300;
